export declare const accessibility: string
export declare const accessibilityFilled: string
export declare const account: string
export declare const accountFilled: string
export declare const addToOrder: string
export declare const addToOrderFilled: string
export declare const adjustment: string
export declare const alcohol: string
export declare const alcoholFilled: string
export declare const appStore: string
export declare const arrowDown: string
export declare const arrowDownSmall: string
export declare const arrowLeft: string
export declare const arrowLeftSmall: string
export declare const arrowRight: string
export declare const arrowRightSmall: string
export declare const arrowUp: string
export declare const arrowUpSmall: string
export declare const backgroundCheck: string
export declare const bag: string
export declare const bagFilled: string
export declare const barcode: string
export declare const bell: string
export declare const bellFilled: string
export declare const browse: string
export declare const browseFilled: string
export declare const calendar: string
export declare const call: string
export declare const callFilled: string
export declare const car: string
export declare const carFilled: string
export declare const cart: string
export declare const cartFilled: string
export declare const categories: string
export declare const categoriesFilled: string
export declare const chat: string
export declare const chatFilled: string
export declare const checkmark: string
export declare const checkmarkCircle: string
export declare const checkmarkCircleDashed: string
export declare const checkmarkCircleFilled: string
export declare const clock: string
export declare const clockFilled: string
export declare const coffee: string
export declare const cold: string
export declare const copy: string
export declare const coupons: string
export declare const couponsFilled: string
export declare const creditCard: string
export declare const delete: string
export declare const deleteFilled: string
export declare const email: string
export declare const emailFilled: string
export declare const facebook: string
export declare const filter: string
export declare const fire: string
export declare const fireFilled: string
export declare const flag: string
export declare const flagFilled: string
export declare const gear: string
export declare const gearFilled: string
export declare const gift: string
export declare const giftcard: string
export declare const glitter: string
export declare const glitterFilled: string
export declare const google: string
export declare const graph: string
export declare const graphFilled: string
export declare const help: string
export declare const helpFilled: string
export declare const home: string
export declare const homeFilled: string
export declare const info: string
export declare const infoFilled: string
export declare const inSeason: string
export declare const inSeasonFilled: string
export declare const instagram: string
export declare const instructions: string
export declare const instructionsFilled: string
export declare const items: string
export declare const itemsFilled: string
export declare const lightbulb: string
export declare const lightbulbFilled: string
export declare const lightning: string
export declare const lightningFilled: string
export declare const like: string
export declare const likeFilled: string
export declare const listsAdd: string
export declare const locationCurrent: string
export declare const locationCurrentFilled: string
export declare const locationMarker: string
export declare const locationMarkerFilled: string
export declare const lock: string
export declare const lockFilled: string
export declare const logout: string
export declare const loyaltyCard: string
export declare const loyaltyCardFilled: string
export declare const menu: string
export declare const minus: string
export declare const money: string
export declare const moneyFilled: string
export declare const moon: string
export declare const moonFilled: string
export declare const more: string
export declare const moreFilled: string
export declare const no: string
export declare const noFilled: string
export declare const office: string
export declare const officeFilled: string
export declare const order: string
export declare const orderFilled: string
export declare const orderIssue: string
export declare const orderIssueFilled: string
export declare const orderReview: string
export declare const orderReviewFilled: string
export declare const orders: string
export declare const ordersFilled: string
export declare const organic: string
export declare const organicFilled: string
export declare const parking: string
export declare const parkingFilled: string
export declare const pencil: string
export declare const pencilFilled: string
export declare const person: string
export declare const personAdd: string
export declare const personAddFilled: string
export declare const personFilled: string
export declare const phone: string
export declare const phoneFilled: string
export declare const photo: string
export declare const photoMissing: string
export declare const pinterest: string
export declare const playStore: string
export declare const plus: string
export declare const reaction: string
export declare const reactionAdd: string
export declare const recipes: string
export declare const recurringOrder: string
export declare const recurringOrderFilled: string
export declare const refund: string
export declare const reorder: string
export declare const reorderFilled: string
export declare const replacement: string
export declare const sale: string
export declare const saleFilled: string
export declare const saveForLater: string
export declare const saveForLaterFilled: string
export declare const scan: string
export declare const scissors: string
export declare const search: string
export declare const sendEmail: string
export declare const sendEmailFilled: string
export declare const share: string
export declare const shareFilled: string
export declare const skip: string
export declare const skipFilled: string
export declare const sort: string
export declare const star: string
export declare const starFilled: string
export declare const store: string
export declare const storeFilled: string
export declare const sunset: string
export declare const sunsetFilled: string
export declare const thumbsDown: string
export declare const thumbsUp: string
export declare const ticket: string
export declare const ticketFilled: string
export declare const tobacco: string
export declare const twitter: string
export declare const unlock: string
export declare const unlockFilled: string
export declare const view: string
export declare const viewFilled: string
export declare const walking: string
export declare const walkingFilled: string
export declare const warning: string
export declare const warningFilled: string
export declare const weight: string
export declare const weightFilled: string
export declare const x: string
export declare const xCircle: string
export declare const xCircleFilled: string
export declare const xSmall: string
export declare const zoomIn: string
export declare const zoomOut: string
